"""created field is_pretest_run in submission table

Revision ID: 0d8403687bdb
Revises: 917c3fd9d676
Create Date: 2025-03-10 23:05:09.400998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8403687bdb'
down_revision: Union[str, None] = 'a84a202cc1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_pretest_run', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'is_pretest_run')
    # ### end Alembic commands ###
