"""implements user's soft deletion

Revision ID: 131c81a29cb0
Revises: 5f047d128cb4
Create Date: 2024-12-11 23:16:32.051209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131c81a29cb0'
down_revision: Union[str, None] = '5f047d128cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_test_cases', 'input',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('problem_test_cases', 'output',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('problem_test_cases', 'input_name')
    op.drop_column('problem_test_cases', 'output_name')
    op.alter_column('submission_results', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('deletion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_date')
    op.alter_column('submission_results', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('problem_test_cases', sa.Column('output_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('problem_test_cases', sa.Column('input_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('problem_test_cases', 'output',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('problem_test_cases', 'input',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
