"""Fixed problem cascade related entity

Revision ID: 1e3763bda634
Revises: cc39690d41d4
Create Date: 2024-12-05 22:54:14.065610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3763bda634'
down_revision: Union[str, None] = 'cc39690d41d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submission_test_cases_submission_id_fkey', 'submission_test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'submission_test_cases', 'submissions', ['submission_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_test_cases', type_='foreignkey')
    op.create_foreign_key('submission_test_cases_submission_id_fkey', 'submission_test_cases', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###
