"""Add code to languages

Revision ID: 2dfdc2cd976f
Revises: 131c81a29cb0
Create Date: 2025-02-12 21:28:02.375706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfdc2cd976f'
down_revision: Union[str, None] = '131c81a29cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'code')
    # ### end Alembic commands ###
