"""various fix

Revision ID: 5f047d128cb4
Revises: 1e3763bda634
Create Date: 2024-12-10 22:19:03.713817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f047d128cb4'
down_revision: Union[str, None] = '1e3763bda634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contest_problems_contest_id_fkey', 'contest_problems', type_='foreignkey')
    op.drop_constraint('contest_problems_problem_id_fkey', 'contest_problems', type_='foreignkey')
    op.create_foreign_key(None, 'contest_problems', 'problems', ['problem_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'contest_problems', 'contests', ['contest_id'], ['id'], ondelete='cascade')
    op.drop_constraint('contest_submissions_submission_id_fkey', 'contest_submissions', type_='foreignkey')
    op.drop_constraint('contest_submissions_contest_id_fkey', 'contest_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'contest_submissions', 'contests', ['contest_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'contest_submissions', 'submissions', ['submission_id'], ['id'], ondelete='cascade')
    op.drop_constraint('contest_users_user_id_fkey', 'contest_users', type_='foreignkey')
    op.drop_constraint('contest_users_contest_id_fkey', 'contest_users', type_='foreignkey')
    op.create_foreign_key(None, 'contest_users', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'contest_users', 'contests', ['contest_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contest_users', type_='foreignkey')
    op.drop_constraint(None, 'contest_users', type_='foreignkey')
    op.create_foreign_key('contest_users_contest_id_fkey', 'contest_users', 'contests', ['contest_id'], ['id'])
    op.create_foreign_key('contest_users_user_id_fkey', 'contest_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'contest_submissions', type_='foreignkey')
    op.drop_constraint(None, 'contest_submissions', type_='foreignkey')
    op.create_foreign_key('contest_submissions_contest_id_fkey', 'contest_submissions', 'contests', ['contest_id'], ['id'])
    op.create_foreign_key('contest_submissions_submission_id_fkey', 'contest_submissions', 'submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'contest_problems', type_='foreignkey')
    op.drop_constraint(None, 'contest_problems', type_='foreignkey')
    op.create_foreign_key('contest_problems_problem_id_fkey', 'contest_problems', 'problems', ['problem_id'], ['id'])
    op.create_foreign_key('contest_problems_contest_id_fkey', 'contest_problems', 'contests', ['contest_id'], ['id'])
    # ### end Alembic commands ###
