"""added submitted_code to submission table

Revision ID: 62c27d68f2b9
Revises: d8039eb83674
Create Date: 2024-09-18 20:53:06.850004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c27d68f2b9'
down_revision: Union[str, None] = 'd8039eb83674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submitted_code', sa.Text, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'submitted_code')
    # ### end Alembic commands ###
