"""added difficulty to problem

Revision ID: 6b6e37b9d9bb
Revises: 9798cc826327
Create Date: 2025-02-19 21:37:31.743580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

difficulties = postgresql.ENUM('EASY','MEDIUM', 'HARD', name='difficulty')


# revision identifiers, used by Alembic.
revision: str = '6b6e37b9d9bb'
down_revision: Union[str, None] = '9798cc826327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    difficulties.create(op.get_bind(),checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('difficulty', difficulties, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'difficulty')
    # ### end Alembic commands ###
    difficulties.drop(op.get_bind(),checkfirst=True)
