"""SubmissionResult code and description modified

Revision ID: 78b93a0defc8
Revises: 9bd649b34176
Create Date: 2024-10-09 20:20:44.347646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b93a0defc8'
down_revision: Union[str, None] = '9bd649b34176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
