"""connect problem test cases to submission test case table

Revision ID: 917c3fd9d676
Revises: a84a202cc1c1
Create Date: 2025-03-09 15:02:57.237395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917c3fd9d676'
down_revision: Union[str, None] = 'a84a202cc1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_test_cases', sa.Column('test_case_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submission_test_cases', 'problem_test_cases', ['test_case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_test_cases', type_='foreignkey')
    op.drop_column('submission_test_cases', 'test_case_id')
    # ### end Alembic commands ###
