"""added contest fields

Revision ID: 9798cc826327
Revises: 2dfdc2cd976f
Create Date: 2025-02-17 17:08:17.186935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9798cc826327'
down_revision: Union[str, None] = '2dfdc2cd976f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('contests', sa.Column('is_registration_open', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'is_registration_open')
    op.drop_column('contests', 'is_public')
    # ### end Alembic commands ###
