"""Fixed problem cascade related entity

Revision ID: cc39690d41d4
Revises: aa82c110adf2
Create Date: 2024-12-05 22:51:18.585135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc39690d41d4'
down_revision: Union[str, None] = 'aa82c110adf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problem_test_cases_problem_id_fkey', 'problem_test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'problem_test_cases', 'problems', ['problem_id'], ['id'], ondelete='cascade')
    op.drop_constraint('submissions_problem_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_problem_id_fkey', 'submissions', 'problems', ['problem_id'], ['id'])
    op.drop_constraint(None, 'problem_test_cases', type_='foreignkey')
    op.create_foreign_key('problem_test_cases_problem_id_fkey', 'problem_test_cases', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###
