"""added input and output to test case

Revision ID: ce238251199b
Revises: 4bb29246fcb8
Create Date: 2024-10-09 21:12:02.489696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce238251199b'
down_revision: Union[str, None] = '4bb29246fcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_test_cases', sa.Column('input', sa.TEXT(), nullable=False))
    op.add_column('problem_test_cases', sa.Column('output', sa.TEXT(), nullable=False))
    op.alter_column('submission_test_cases', 'memory',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('submission_test_cases', 'time',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('submission_test_cases', 'input_name')
    op.alter_column('submissions', 'submitted_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'submitted_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('submission_test_cases', sa.Column('input_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('submission_test_cases', 'time',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('submission_test_cases', 'memory',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('problem_test_cases', 'output')
    op.drop_column('problem_test_cases', 'input')
    # ### end Alembic commands ###
