"""update submission table

Revision ID: d8039eb83674
Revises: d97da3613f26
Create Date: 2024-09-12 15:54:16.631307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8039eb83674'
down_revision: Union[str, None] = 'd97da3613f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'submission_result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'submission_result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
