"""SubmissionResult code and description modified

Revision ID: decc08ba5bab
Revises: 78b93a0defc8
Create Date: 2024-10-09 20:21:52.144919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decc08ba5bab'
down_revision: Union[str, None] = '78b93a0defc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission_results', 'code',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('submission_results', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission_results', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('submission_results', 'code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
