services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER} 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - byteblitz
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "15432:80"
    networks:
      - byteblitz
    restart: unless-stopped

  app:
    container_name: byteblitz-backend
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - byteblitz
    command: python main.py

networks:
  byteblitz:
    driver: bridge

volumes:
    postgres:
    pgadmin: